"""new

Revision ID: 1e20ee77bb98
Revises: 326385_change_warehouse_to_foreign_key
Create Date: 2026-06-30 19:01:05.710728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e20ee77bb98'
down_revision: Union[str, None] = '326385_change_warehouse_to_foreign_key'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
