"""add_test_type_and_file_hash

Revision ID: 44e1506dbe10
Revises: b1aeef9c142d
Create Date: 2026-06-29 00:03:04.368054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e1506dbe10'
down_revision: Union[str, None] = 'b1aeef9c142d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_attachments', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_experiment_attachments_file_hash'), 'experiment_attachments', ['file_hash'], unique=False)
    op.add_column('experiment_records', sa.Column('test_type', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_experiment_records_test_type'), 'experiment_records', ['test_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_records_test_type'), table_name='experiment_records')
    op.drop_column('experiment_records', 'test_type')
    op.drop_index(op.f('ix_experiment_attachments_file_hash'), table_name='experiment_attachments')
    op.drop_column('experiment_attachments', 'file_hash')
    # ### end Alembic commands ###
